project:
  type: book
  output-dir: _book
  resources:
    - .nojekyll
  pre-render: assets/_refs.r

execute: 
  cache: true
  freeze: auto

book:
  google-analytics: G-6LLMGL3T2Q
  title: "Advanced biostatistics and Open science"
  subtitle: "Lab manual for BIO8940"
  description: "Include extra information and exercises"
  author: Julien Martin
  date: today
  date-format: iso 
  reader-mode: true
  search: true
  page-footer:
    left: |
      By Julien Martin.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/blue_dragon.jpg
  favicon: cover.jpg
  site-url: https://biostats-uottawa.github.io/bio8940_manual/
  repo-url: https://github.com/biostats-uottawa/bio8940_manual/
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  navbar:
    background: light
#    logo: quarto.png
#    logo-alt: "Quarto logo."
    collapse-below: lg
    title: "BIO8940: manual"
    left:
      - text: Course
        href: https://biostats-uottawa.github.io/bio8940_course/
      - text: Data
        href: https://biostats-uottawa.github.io/bio8940_course/dataset.html
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Biostats avec R (Bio4558)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: R-way to hell (R book)
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R (livre R)
            href: https://biostats-uottawa.github.io/R/fr/

  chapters:
    - index.Rmd
    - part: "Open Science"
      chapters:
        - open_science.Rmd
        - rmarkdown.Rmd
        - github.Rmd
    - part: Statistics
      chapters:
        - glm.Rmd
        - lmm.Rmd
        - intro_glmm.Rmd
        - intro_bayesian.Rmd
        - multivar.Rmd
        - randreg.Rmd
        - beyond_p.Rmd
    - references.qmd
  appendices:
    - app-R.Rmd

bibliography: [assets/book.bib, assets/grateful-refs.bib]
biblio-style: apalike
csl: assets/ecology.csl

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
      #- r4ds.scss
    css: css/style.css
    code-link: true

    author-meta: "Julien Martin"
    callout-appearance: simple

  pdf:
    documentclass: scrbook
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    toc-depth: 2
    pdf-engine: lualatex

  epub:
    dev: svglite
    stylesheet: css/epub.css
    toc: true

editor: visual