<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.2 Practical | BIO8940 Advanced stats and Open Science</title>
  <meta name="description" content="Theory and practicals for BIO8940 course at the University of Ottawa" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="6.2 Practical | BIO8940 Advanced stats and Open Science" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Theory and practicals for BIO8940 course at the University of Ottawa" />
  <meta name="github-repo" content="BIO8940-uOttawa/class_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.2 Practical | BIO8940 Advanced stats and Open Science" />
  
  <meta name="twitter:description" content="Theory and practicals for BIO8940 course at the University of Ottawa" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="6.1-lecture-5.html"/>
<link rel="next" href="7-introduction-to-bayesian-inference.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Advanced stats and open science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a>
<ul>
<li class="chapter" data-level="" data-path="quelques-points-importants-à-retenir.html"><a href="quelques-points-importants-à-retenir.html"><i class="fa fa-check"></i>Quelques points importants à retenir</a></li>
<li class="chapter" data-level="" data-path="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><a href="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><i class="fa fa-check"></i>Qu’est-ce que R et pourquoi l’utiliser dans ce cours?</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html"><i class="fa fa-check"></i>Installation des logiciels nécessaires</a>
<ul>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="0.0.1" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#text-editor-or-ide"><i class="fa fa-check"></i><b>0.0.1</b> Text editor or IDE</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#paquets-pour-r"><i class="fa fa-check"></i>Paquets pour R</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#pandoc"><i class="fa fa-check"></i>pandoc</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#latex"><i class="fa fa-check"></i>laTex</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="instructions-générales-pour-les-laboratoires.html"><a href="instructions-générales-pour-les-laboratoires.html"><i class="fa fa-check"></i>Instructions générales pour les laboratoires</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html"><i class="fa fa-check"></i>Notes sur le manuel</a>
<ul>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#licence"><i class="fa fa-check"></i>Licence</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Open Science</b></span></li>
<li class="chapter" data-level="1" data-path="1-introduction-to-open-science.html"><a href="1-introduction-to-open-science.html"><i class="fa fa-check"></i><b>1</b> Introduction to open Science</a>
<ul>
<li class="chapter" data-level="1.1" data-path="1.1-why-do-we-need-it.html"><a href="1.1-why-do-we-need-it.html"><i class="fa fa-check"></i><b>1.1</b> Why do we need it?</a></li>
<li class="chapter" data-level="1.2" data-path="1.2-lecture.html"><a href="1.2-lecture.html"><i class="fa fa-check"></i><b>1.2</b> Lecture</a></li>
<li class="chapter" data-level="1.3" data-path="1.3-what-it-is.html"><a href="1.3-what-it-is.html"><i class="fa fa-check"></i><b>1.3</b> What it is?</a></li>
<li class="chapter" data-level="1.4" data-path="1.4-reproducible-code-and-analysis.html"><a href="1.4-reproducible-code-and-analysis.html"><i class="fa fa-check"></i><b>1.4</b> Reproducible code and analysis</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-introduction-to-rmarkdown.html"><a href="2-introduction-to-rmarkdown.html"><i class="fa fa-check"></i><b>2</b> Introduction to Rmarkdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2.1-lecture-1.html"><a href="2.1-lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a></li>
<li class="chapter" data-level="2.2" data-path="2.2-practical.html"><a href="2.2-practical.html"><i class="fa fa-check"></i><b>2.2</b> Practical</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="2.2-practical.html"><a href="2.2-practical.html#context"><i class="fa fa-check"></i><b>2.2.1</b> Context</a></li>
<li class="chapter" data-level="2.2.2" data-path="2.2-practical.html"><a href="2.2-practical.html#questions"><i class="fa fa-check"></i><b>2.2.2</b> Questions</a></li>
<li class="chapter" data-level="" data-path="2.2-practical.html"><a href="2.2-practical.html#example-of-output"><i class="fa fa-check"></i>Example of output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-introduction-to-github-with-r.html"><a href="3-introduction-to-github-with-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to github with R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3.1-lecture-2.html"><a href="3.1-lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a></li>
<li class="chapter" data-level="3.2" data-path="3.2-practical-1.html"><a href="3.2-practical-1.html"><i class="fa fa-check"></i><b>3.2</b> Practical</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="3.2-practical-1.html"><a href="3.2-practical-1.html#context-1"><i class="fa fa-check"></i><b>3.2.1</b> Context</a></li>
<li class="chapter" data-level="3.2.2" data-path="3.2-practical-1.html"><a href="3.2-practical-1.html#information-of-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Information of the data</a></li>
<li class="chapter" data-level="3.2.3" data-path="3.2-practical-1.html"><a href="3.2-practical-1.html#questions-1"><i class="fa fa-check"></i><b>3.2.3</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Statistics</b></span></li>
<li class="chapter" data-level="4" data-path="4-generalized-linear-model-glm.html"><a href="4-generalized-linear-model-glm.html"><i class="fa fa-check"></i><b>4</b> Generalized linear model, <code>glm</code></a>
<ul>
<li class="chapter" data-level="4.1" data-path="4.1-lecture-3.html"><a href="4.1-lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="4.1-lecture-3.html"><a href="4.1-lecture-3.html#distributions"><i class="fa fa-check"></i><b>4.1.1</b> Distributions</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4.2-practical-2.html"><a href="4.2-practical-2.html"><i class="fa fa-check"></i><b>4.2</b> Practical</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="4.2-practical-2.html"><a href="4.2-practical-2.html#logistic-regression"><i class="fa fa-check"></i><b>4.2.1</b> Logistic regression</a></li>
<li class="chapter" data-level="4.2.2" data-path="4.2-practical-2.html"><a href="4.2-practical-2.html#poisson-regression"><i class="fa fa-check"></i><b>4.2.2</b> Poisson regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-introduction-to-linear-mixed-models.html"><a href="5-introduction-to-linear-mixed-models.html"><i class="fa fa-check"></i><b>5</b> Introduction to linear mixed models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5.1-lecture-4.html"><a href="5.1-lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="5.1-lecture-4.html"><a href="5.1-lecture-4.html#testing-fixed-effects"><i class="fa fa-check"></i><b>5.1.1</b> Testing fixed effects</a></li>
<li class="chapter" data-level="5.1.2" data-path="5.1-lecture-4.html"><a href="5.1-lecture-4.html#shrinkage"><i class="fa fa-check"></i><b>5.1.2</b> Shrinkage</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html"><i class="fa fa-check"></i><b>5.2</b> Practical</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#overview"><i class="fa fa-check"></i><b>5.2.1</b> Overview</a></li>
<li class="chapter" data-level="5.2.2" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#r-packages-needed"><i class="fa fa-check"></i><b>5.2.2</b> R packages needed</a></li>
<li class="chapter" data-level="5.2.3" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#the-superb-wild-unicorns-of-the-scottish-highlands"><i class="fa fa-check"></i><b>5.2.3</b> The superb wild unicorns of the Scottish Highlands</a></li>
<li class="chapter" data-level="5.2.4" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#do-unicorns-differ-in-aggressiveness-your-first-mixed-model"><i class="fa fa-check"></i><b>5.2.4</b> Do unicorns differ in aggressiveness? Your first mixed model</a></li>
<li class="chapter" data-level="5.2.5" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#do-unicorns-differ-in-aggressiveness-a-better-mixed-model"><i class="fa fa-check"></i><b>5.2.5</b> Do unicorns differ in aggressiveness? A better mixed model</a></li>
<li class="chapter" data-level="5.2.6" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#what-is-the-repeatability"><i class="fa fa-check"></i><b>5.2.6</b> What is the repeatability?</a></li>
<li class="chapter" data-level="5.2.7" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#a-quick-note-on-uncertainty"><i class="fa fa-check"></i><b>5.2.7</b> A quick note on uncertainty</a></li>
<li class="chapter" data-level="5.2.8" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#an-easy-way-to-mess-up-your-mixed-models"><i class="fa fa-check"></i><b>5.2.8</b> An easy way to mess up your mixed models</a></li>
<li class="chapter" data-level="5.2.9" data-path="5.2-practical-3.html"><a href="5.2-practical-3.html#happy-mixed-modelling"><i class="fa fa-check"></i><b>5.2.9</b> Happy mixed-modelling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-introduction-to-glmm.html"><a href="6-introduction-to-glmm.html"><i class="fa fa-check"></i><b>6</b> Introduction to <code>GLMM</code></a>
<ul>
<li class="chapter" data-level="6.1" data-path="6.1-lecture-5.html"><a href="6.1-lecture-5.html"><i class="fa fa-check"></i><b>6.1</b> Lecture</a></li>
<li class="chapter" data-level="6.2" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html"><i class="fa fa-check"></i><b>6.2</b> Practical</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#packages-and-functions"><i class="fa fa-check"></i><b>6.2.1</b> Packages and functions</a></li>
<li class="chapter" data-level="6.2.2" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#the-data-set"><i class="fa fa-check"></i><b>6.2.2</b> The data set</a></li>
<li class="chapter" data-level="6.2.3" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#specifying-fixed-and-random-effects"><i class="fa fa-check"></i><b>6.2.3</b> Specifying fixed and random Effects</a></li>
<li class="chapter" data-level="6.2.4" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#look-at-overall-patterns-in-data"><i class="fa fa-check"></i><b>6.2.4</b> Look at overall patterns in data</a></li>
<li class="chapter" data-level="6.2.5" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#choose-an-error-distribution"><i class="fa fa-check"></i><b>6.2.5</b> Choose an error distribution</a></li>
<li class="chapter" data-level="6.2.6" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#fitting-group-wise-glm"><i class="fa fa-check"></i><b>6.2.6</b> Fitting group-wise GLM</a></li>
<li class="chapter" data-level="6.2.7" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#fitting-and-evaluating-glmms"><i class="fa fa-check"></i><b>6.2.7</b> Fitting and evaluating GLMMs</a></li>
<li class="chapter" data-level="6.2.8" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#inference"><i class="fa fa-check"></i><b>6.2.8</b> Inference</a></li>
<li class="chapter" data-level="6.2.9" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#conclusions"><i class="fa fa-check"></i><b>6.2.9</b> Conclusions</a></li>
<li class="chapter" data-level="6.2.10" data-path="6.2-practical-4.html"><a href="6.2-practical-4.html#happy-generalized-mixed-modelling"><i class="fa fa-check"></i><b>6.2.10</b> Happy generalized mixed-modelling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-introduction-to-bayesian-inference.html"><a href="7-introduction-to-bayesian-inference.html"><i class="fa fa-check"></i><b>7</b> Introduction to <code>Bayesian Inference</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="7.1-lecture-6.html"><a href="7.1-lecture-6.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="7.1-lecture-6.html"><a href="7.1-lecture-6.html#bayes-theorem"><i class="fa fa-check"></i><b>7.1.1</b> Bayes’ theorem</a></li>
<li class="chapter" data-level="7.1.2" data-path="7.1-lecture-6.html"><a href="7.1-lecture-6.html#intro-to-mcmc"><i class="fa fa-check"></i><b>7.1.2</b> Intro to MCMC</a></li>
<li class="chapter" data-level="7.1.3" data-path="7.1-lecture-6.html"><a href="7.1-lecture-6.html#inferences-1"><i class="fa fa-check"></i><b>7.1.3</b> Inferences</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html"><i class="fa fa-check"></i><b>7.2</b> Practical</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#r-packages-needed-1"><i class="fa fa-check"></i><b>7.2.1</b> R packages needed</a></li>
<li class="chapter" data-level="7.2.2" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#a-refresher-on-unicorn-ecology"><i class="fa fa-check"></i><b>7.2.2</b> A refresher on unicorn ecology</a></li>
<li class="chapter" data-level="7.2.3" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#mcmcglmm"><i class="fa fa-check"></i><b>7.2.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="7.2.4" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#inferences-2"><i class="fa fa-check"></i><b>7.2.4</b> Inferences</a></li>
<li class="chapter" data-level="7.2.5" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#brms"><i class="fa fa-check"></i><b>7.2.5</b> brms</a></li>
<li class="chapter" data-level="7.2.6" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#inferences-3"><i class="fa fa-check"></i><b>7.2.6</b> Inferences</a></li>
<li class="chapter" data-level="7.2.7" data-path="7.2-practical-5.html"><a href="7.2-practical-5.html#happy-bayesian-stats"><i class="fa fa-check"></i><b>7.2.7</b> Happy Bayesian stats</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-multivariate-mixed-models.html"><a href="8-multivariate-mixed-models.html"><i class="fa fa-check"></i><b>8</b> Multivariate mixed models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="8.1-lecture-7.html"><a href="8.1-lecture-7.html"><i class="fa fa-check"></i><b>8.1</b> Lecture</a></li>
<li class="chapter" data-level="8.2" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html"><i class="fa fa-check"></i><b>8.2</b> Practical</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html#r-packages-needed-2"><i class="fa fa-check"></i><b>8.2.1</b> R packages needed</a></li>
<li class="chapter" data-level="8.2.2" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html#the-blue-dragon-of-the-east"><i class="fa fa-check"></i><b>8.2.2</b> The blue dragon of the East</a></li>
<li class="chapter" data-level="8.2.3" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html#multiple-univariate-models"><i class="fa fa-check"></i><b>8.2.3</b> Multiple univariate models</a></li>
<li class="chapter" data-level="8.2.4" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html#multivariate-approach"><i class="fa fa-check"></i><b>8.2.4</b> Multivariate approach</a></li>
<li class="chapter" data-level="8.2.5" data-path="8.2-practical-6.html"><a href="8.2-practical-6.html#happy-multivariate-models"><i class="fa fa-check"></i><b>8.2.5</b> Happy multivariate models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-random-regression-and-character-state-approaches.html"><a href="9-random-regression-and-character-state-approaches.html"><i class="fa fa-check"></i><b>9</b> Random regression and character state approaches</a>
<ul>
<li class="chapter" data-level="9.1" data-path="9.1-lecture-8.html"><a href="9.1-lecture-8.html"><i class="fa fa-check"></i><b>9.1</b> Lecture</a></li>
<li class="chapter" data-level="9.2" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html"><i class="fa fa-check"></i><b>9.2</b> Practical</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#r-packages-needed-3"><i class="fa fa-check"></i><b>9.2.1</b> R packages needed</a></li>
<li class="chapter" data-level="9.2.2" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#refresher-on-unicorn-aggression"><i class="fa fa-check"></i><b>9.2.2</b> Refresher on unicorn aggression</a></li>
<li class="chapter" data-level="9.2.3" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#random-regression"><i class="fa fa-check"></i><b>9.2.3</b> Random regression</a></li>
<li class="chapter" data-level="9.2.4" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#character-state-approach"><i class="fa fa-check"></i><b>9.2.4</b> Character-State approach</a></li>
<li class="chapter" data-level="9.2.5" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#from-random-regression-to-character-state"><i class="fa fa-check"></i><b>9.2.5</b> From random regression to character-state</a></li>
<li class="chapter" data-level="9.2.6" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#conclusions-2"><i class="fa fa-check"></i><b>9.2.6</b> Conclusions</a></li>
<li class="chapter" data-level="9.2.7" data-path="9.2-practical-7.html"><a href="9.2-practical-7.html#happy-multivariate-models-1"><i class="fa fa-check"></i><b>9.2.7</b> Happy multivariate models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="10-beyong-p-0.html"><a href="10-beyong-p-0.html"><i class="fa fa-check"></i><b>10</b> Beyong <em>P &lt; 0.05</em></a></li>
<li class="part"><span><b>III Appendix</b></span></li>
<li class="chapter" data-level="" data-path="r-1.html"><a href="r-1.html"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="to-do-list.html"><a href="to-do-list.html"><i class="fa fa-check"></i>To do list</a>
<ul>
<li class="chapter" data-level="10.1" data-path="10.1-potential-structure.html"><a href="10.1-potential-structure.html"><i class="fa fa-check"></i><b>10.1</b> potential structure</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO8940 Advanced stats and Open Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="practical-4" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Practical</h2>
<p>This is an adapted version largely inspired by the tutorial in <span class="citation">(Bolker et al. <a href="#ref-bolker_generalized_2009" role="doc-biblioref">2009</a>)</span>.
Spatial variation in nutrient availability and herbivory is likely to cause population differentiation and maintain genetic diversity in plant populations.Here we measure the extent to which mouse-ear cress (Arabidopsis thaliana)exhibits population and genotypic variation in their responses to these im-portant environmental factors. We are particularly interested in whether these populations exhibit nutrient mediated compensation, where higher nutrient levels allow genotypes to better tolerate herbivory <span class="citation">(Banta et al. <a href="#ref-banta_comprehensive_2010" role="doc-biblioref">2010</a>)</span>. We use GLMMs to estimate the effect of nutrient levels, simulated herbivory, and their interaction on fruit production in Arabidopsis thaliana(fixed effects), and the extent to which populations vary in their responses(random effects, or variance components)</p>
<div id="packages-and-functions" class="section level3" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Packages and functions</h3>
<p>You need to download the “extra_funs.R” script for some functions used in the Practical</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="6.2-practical-4.html#cb98-1" aria-hidden="true"></a><span class="kw">library</span>(lme4)</span>
<span id="cb98-2"><a href="6.2-practical-4.html#cb98-2" aria-hidden="true"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb98-3"><a href="6.2-practical-4.html#cb98-3" aria-hidden="true"></a><span class="kw">library</span>(patchwork)</span>
<span id="cb98-4"><a href="6.2-practical-4.html#cb98-4" aria-hidden="true"></a><span class="kw">library</span>(lattice)</span>
<span id="cb98-5"><a href="6.2-practical-4.html#cb98-5" aria-hidden="true"></a><span class="kw">library</span>(DHARMa)</span>
<span id="cb98-6"><a href="6.2-practical-4.html#cb98-6" aria-hidden="true"></a><span class="kw">source</span>(<span class="st">&quot;data/extra_funs.R&quot;</span>)</span></code></pre></div>
</div>
<div id="the-data-set" class="section level3" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> The data set</h3>
<p>In this data set, the response variable is the number of fruits (i.e. seed capsules) per plant. The number of fruits produced by an individual plant(the experimental unit) was hypothesized to be a function of fixed effects,including nutrient levels (low vs. high), simulated herbivory (none vs. apical meristem damage), region (Sweden, Netherlands, Spain), and interactions among these. Fruit number was also a function of random effects including both the population and individual genotype. Because Arabidopsis is highly selfing, seeds of a single individual served as replicates of that individual.There were also nuisance variables, including the placement of the plant in the greenhouse, and the method used to germinate seeds. These were estimated as fixed effects but interactions were excluded.</p>
<ul>
<li><code>X</code> observation number (we will use this observation number later, when we are accounting for overdispersion)</li>
<li><code>reg</code> a factor for region (Netherlands, Spain, Sweden).</li>
<li><code>popu</code> a factor with a level for each population.</li>
<li><code>gen</code> a factor with a level for each genotype.</li>
<li><code>rack</code> a nuisance factor for one of two greenhouse racks.</li>
<li><code>nutrient</code> a factor with levels for minimal or additional nutrients.</li>
<li><code>amd</code> a factor with levels for no damage or simulated herbivory (apical meristem damage; we will sometimes refer to this as “clipping”)</li>
<li><code>status</code> a nuisance factor for germination method.</li>
<li><code>total.fruits</code> the response; an integer count of the number of fruits per plant.</li>
</ul>
</div>
<div id="specifying-fixed-and-random-effects" class="section level3" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Specifying fixed and random Effects</h3>
<p>Here we need to select a realistic full model, based on the scientific questions and the data actually at hand. We first load the data set and make sure that each variable is appropriately designated as numeric or factor (i.e.categorical variable).</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="6.2-practical-4.html#cb99-1" aria-hidden="true"></a>dat_tf &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Banta_TotalFruits.csv&quot;</span>)</span>
<span id="cb99-2"><a href="6.2-practical-4.html#cb99-2" aria-hidden="true"></a><span class="kw">str</span>(dat_tf)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    625 obs. of  9 variables:
##  $ X           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ reg         : chr  &quot;NL&quot; &quot;NL&quot; &quot;NL&quot; &quot;NL&quot; ...
##  $ popu        : chr  &quot;3.NL&quot; &quot;3.NL&quot; &quot;3.NL&quot; &quot;3.NL&quot; ...
##  $ gen         : int  4 4 4 4 4 4 4 4 4 5 ...
##  $ rack        : int  2 1 1 2 2 2 2 1 2 1 ...
##  $ nutrient    : int  1 1 1 1 8 1 1 1 8 1 ...
##  $ amd         : chr  &quot;clipped&quot; &quot;clipped&quot; &quot;clipped&quot; &quot;clipped&quot; ...
##  $ status      : chr  &quot;Transplant&quot; &quot;Petri.Plate&quot; &quot;Normal&quot; &quot;Normal&quot; ...
##  $ total.fruits: int  0 0 0 0 0 0 0 3 2 0 ...</code></pre>
<p>The <code>X</code>, <code>gen</code>, <code>rack</code> and <code>nutrient</code> variables are coded as integers, but we want them to be factors.
 We use <code>mutate()</code> <code>dplyr</code> 📦, which operates within the data set, to avoid typing lots of commands like <code>dat_tf$rack &lt;- factor(dat_tf$rack)</code>
 At the same time, we reorder the <code>clipping</code> variable so that <code>"unclipped"</code> is the reference level (we could also have used <code>relevel(amd,"unclipped")</code>).</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="6.2-practical-4.html#cb101-1" aria-hidden="true"></a>dat_tf &lt;-<span class="st"> </span><span class="kw">mutate</span>(</span>
<span id="cb101-2"><a href="6.2-practical-4.html#cb101-2" aria-hidden="true"></a>  dat_tf,</span>
<span id="cb101-3"><a href="6.2-practical-4.html#cb101-3" aria-hidden="true"></a>  <span class="dt">X =</span> <span class="kw">factor</span>(X),</span>
<span id="cb101-4"><a href="6.2-practical-4.html#cb101-4" aria-hidden="true"></a>  <span class="dt">gen =</span> <span class="kw">factor</span>(gen),</span>
<span id="cb101-5"><a href="6.2-practical-4.html#cb101-5" aria-hidden="true"></a>  <span class="dt">rack =</span> <span class="kw">factor</span>(rack),</span>
<span id="cb101-6"><a href="6.2-practical-4.html#cb101-6" aria-hidden="true"></a>  <span class="dt">amd =</span> <span class="kw">factor</span>(amd, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;unclipped&quot;</span>, <span class="st">&quot;clipped&quot;</span>)),</span>
<span id="cb101-7"><a href="6.2-practical-4.html#cb101-7" aria-hidden="true"></a>  <span class="dt">nutrient =</span> <span class="kw">factor</span>(nutrient, <span class="dt">label =</span> <span class="kw">c</span>(<span class="st">&quot;Low&quot;</span>, <span class="st">&quot;High&quot;</span>))</span>
<span id="cb101-8"><a href="6.2-practical-4.html#cb101-8" aria-hidden="true"></a>)</span></code></pre></div>
<p>Now we check replication for each genotype (columns) within each population (rows).</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="6.2-practical-4.html#cb102-1" aria-hidden="true"></a>(reptab &lt;-<span class="st"> </span><span class="kw">with</span>(dat_tf, <span class="kw">table</span>(popu, gen)))</span></code></pre></div>
<pre><code>##       gen
## popu    4  5  6 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 30 34 35
##   1.SP  0  0  0  0  0 39 26 35  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
##   1.SW  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28 20  0  0  0  0
##   2.SW  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 18 14  0  0
##   3.NL 31 11 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
##   5.NL  0  0  0 35 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
##   5.SP  0  0  0  0  0  0  0  0 43 22 12  0  0  0  0  0  0  0  0  0  0  0  0
##   6.SP  0  0  0  0  0  0  0  0  0  0  0 13 24 14  0  0  0  0  0  0  0  0  0
##   7.SW  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 45 47
##   8.SP  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13 16 35  0  0  0  0  0  0
##       gen
## popu   36
##   1.SP  0
##   1.SW  0
##   2.SW  0
##   3.NL  0
##   5.NL  0
##   5.SP  0
##   6.SP  0
##   7.SW 45
##   8.SP  0</code></pre>

<div class="rmdcode">
<p><strong>Exercise</strong>: this mode of inspection is OK for this data set but might fail for much larger data sets or for more levels of nesting. See if you can think of some other numerical or graphical methods for inspecting the structure of data sets.</p>
<ol style="list-style-type: decimal">
<li>plot(reptab) gives a mosaic plot of the two-way table; examine this, see if you can figure out how to interpret it, and decide whether you think it might be useful</li>
<li>try the commands colSums(reptab&gt;0) (and the equivalent for rowSums) and figure out what they are telling you.</li>
<li>Using this recipe, how would you compute the range of number of genotypes per treatment combination?</li>
</ol>
</div>
<div class="exer">
<ol style="list-style-type: decimal">
<li>Do you find the mosaic plot you obtained ugly and super hard to read? Me too 🤣</li>
</ol>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="6.2-practical-4.html#cb104-1" aria-hidden="true"></a><span class="kw">plot</span>(reptab)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-52"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-52-1.svg" alt="A truly useless plot no one can understand" width="672" />
<p class="caption">
Figure 6.2: A truly useless plot no one can understand
</p>
</div>
<ol start="2" style="list-style-type: decimal">
<li><code>colSums()</code> do the sum of all the rows for each columns of a table. So <code>colSums(reptab&gt;0)</code> gives you for each genotype the number of populations (lines) where you have at least 1 observations.</li>
</ol>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="6.2-practical-4.html#cb105-1" aria-hidden="true"></a><span class="kw">colSums</span>(reptab <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>##  4  5  6 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 30 34 35 36 
##  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="6.2-practical-4.html#cb107-1" aria-hidden="true"></a><span class="kw">rowSums</span>(reptab <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 1.SP 1.SW 2.SW 3.NL 5.NL 5.SP 6.SP 7.SW 8.SP 
##    3    2    2    3    2    3    3    3    3</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>You firts need to create a new table of number of observations per treatment and genotypes</li>
</ol>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="6.2-practical-4.html#cb109-1" aria-hidden="true"></a>reptab2 &lt;-<span class="st"> </span><span class="kw">with</span>(dat_tf, <span class="kw">table</span>(<span class="kw">paste</span>(amd, nutrient, <span class="dt">sep =</span> <span class="st">&quot;_&quot;</span>), gen))</span>
<span id="cb109-2"><a href="6.2-practical-4.html#cb109-2" aria-hidden="true"></a><span class="kw">range</span>(reptab2)</span></code></pre></div>
<pre><code>## [1]  2 13</code></pre>
</div>
<p>This reveals that we have only 2–4 populations per region and 2–3 genotypes per population. However, we also have 2–13 replicates per genotype for each treatment combination (four unique treatment combinations: 2 levels of nutrients by 2 levels of simulated herbivory). Thus, even though this was a reasonably large experiment (625 plants), there were a very small number of replicates with which to estimate variance components, and many more potential interactions than our data can support. Therefore, judicious selection of model terms, based on both biology and the data, is warranted. We note that we don’t really have enough levels per random effect, nor enough replication per unique treatment combination. Therefore, we decide to omit the fixed effect of “region”, although we recognize that populations in different regions are widely geographically separated.</p>
<p>However, as in all GLMMs where the scale parameter is treated as fixed and deviations from the fixed scale parameter would be identifiable (i.e. Poisson and binomial (N &gt; 1), but not binary, models) we may have to deal with overdispersion.</p>
</div>
<div id="look-at-overall-patterns-in-data" class="section level3" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Look at overall patterns in data</h3>
<p>I usually like to start with a relatively simple overall plot of the data, disregarding the random factors, just to see what’s going on. For reasons to be discussed below, we choose to look at the data on the log (or log(1 + x) scale. Let’s plot either box-and-whisker plots (useful summaries) or dot plots (more detailed, good for seeing if we missed anything).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-55"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-55-1.svg" alt="Number of fruits (log + 1) as a function of treatments" width="672" />
<p class="caption">
Figure 6.3: Number of fruits (log + 1) as a function of treatments
</p>
</div>

<div class="rmdcode">
<strong>Exercise</strong> generate these plots and figure out how they work before continuing. Try conditioning/faceting on population rather than region: for facet_wrap you might want to take out the nrow = 1 specification. If you want try reorder the subplots by overall mean fruit set and/or colour the points according to the region they come from.
</div>
<div class="exer">
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="6.2-practical-4.html#cb111-1" aria-hidden="true"></a>p1 &lt;-<span class="st"> </span><span class="kw">qplot</span>(</span>
<span id="cb111-2"><a href="6.2-practical-4.html#cb111-2" aria-hidden="true"></a>    <span class="kw">interaction</span>(nutrient, amd),</span>
<span id="cb111-3"><a href="6.2-practical-4.html#cb111-3" aria-hidden="true"></a>    <span class="kw">log</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>total.fruits),</span>
<span id="cb111-4"><a href="6.2-practical-4.html#cb111-4" aria-hidden="true"></a>    <span class="dt">data =</span> dat_tf, <span class="dt">geom =</span> <span class="st">&quot;boxplot&quot;</span>) <span class="op">+</span></span>
<span id="cb111-5"><a href="6.2-practical-4.html#cb111-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>reg, <span class="dt">nrow =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb111-6"><a href="6.2-practical-4.html#cb111-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>)) <span class="op">+</span></span>
<span id="cb111-7"><a href="6.2-practical-4.html#cb111-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Boxplot&quot;</span>)</span>
<span id="cb111-8"><a href="6.2-practical-4.html#cb111-8" aria-hidden="true"></a>p2 &lt;-<span class="st"> </span><span class="kw">qplot</span>(</span>
<span id="cb111-9"><a href="6.2-practical-4.html#cb111-9" aria-hidden="true"></a>    <span class="kw">interaction</span>(nutrient, amd),</span>
<span id="cb111-10"><a href="6.2-practical-4.html#cb111-10" aria-hidden="true"></a>    <span class="kw">log</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>total.fruits),</span>
<span id="cb111-11"><a href="6.2-practical-4.html#cb111-11" aria-hidden="true"></a>    <span class="dt">data =</span> dat_tf) <span class="op">+</span></span>
<span id="cb111-12"><a href="6.2-practical-4.html#cb111-12" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>reg, <span class="dt">nrow =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb111-13"><a href="6.2-practical-4.html#cb111-13" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_sum</span>() <span class="op">+</span></span>
<span id="cb111-14"><a href="6.2-practical-4.html#cb111-14" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>)) <span class="op">+</span></span>
<span id="cb111-15"><a href="6.2-practical-4.html#cb111-15" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Dot plot&quot;</span>)</span>
<span id="cb111-16"><a href="6.2-practical-4.html#cb111-16" aria-hidden="true"></a>p1 <span class="op">+</span><span class="st"> </span>p2</span></code></pre></div>
</div>
</div>
<div id="choose-an-error-distribution" class="section level3" number="6.2.5">
<h3><span class="header-section-number">6.2.5</span> Choose an error distribution</h3>
<p>The data are non-normal in principle (i.e., count data, so our first guess would be a Poisson distribution). If we transform total fruits with the canonical link function (log), we hope to see relatively homogeneous variances across categories and groups.</p>
<p>First we define a new factor that represents every combination of genotype and treatment (nutrient × clipping) treatment, and sort it in order of increasing mean fruit set.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="6.2-practical-4.html#cb112-1" aria-hidden="true"></a>dat_tf &lt;-<span class="st"> </span>dat_tf <span class="op">%&gt;%</span></span>
<span id="cb112-2"><a href="6.2-practical-4.html#cb112-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb112-3"><a href="6.2-practical-4.html#cb112-3" aria-hidden="true"></a>    <span class="dt">gna =</span> <span class="kw">reorder</span>(<span class="kw">interaction</span>(gen, nutrient, amd), total.fruits, mean)</span>
<span id="cb112-4"><a href="6.2-practical-4.html#cb112-4" aria-hidden="true"></a>  )</span></code></pre></div>
<p>Now time to plot it</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="6.2-practical-4.html#cb113-1" aria-hidden="true"></a><span class="kw">ggplot</span>(dat_tf, <span class="kw">aes</span>(<span class="dt">x =</span> gna, <span class="dt">y =</span> <span class="kw">log</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>total.fruits))) <span class="op">+</span></span>
<span id="cb113-2"><a href="6.2-practical-4.html#cb113-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb113-3"><a href="6.2-practical-4.html#cb113-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb113-4"><a href="6.2-practical-4.html#cb113-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-59"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-59-1.svg" alt="Boxplot of total fruits (log + 1) per genotypes and treatments" width="672" />
<p class="caption">
Figure 6.4: Boxplot of total fruits (log + 1) per genotypes and treatments
</p>
</div>
<p>We could also calculate the variance for each genotype × treatment combination and provide a statistical summary of these variances.
This reveals substantial variation among the sample variances on the transformed data. In addition to heterogeneous variances across groups, Figure 1 reveals many zeroes in groups, and some groups with a mean and variance of zero, further suggesting we need a non-normal error distribution, and perhaps something other than a Poisson distribution.</p>
<p>We could calculate λ(mean) for each genotype × treatment combination and provide a statistical summary of each group’s λ.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="6.2-practical-4.html#cb114-1" aria-hidden="true"></a>grp_means &lt;-<span class="st"> </span><span class="kw">with</span>(dat_tf, <span class="kw">tapply</span>(total.fruits, <span class="kw">list</span>(gna), mean))</span>
<span id="cb114-2"><a href="6.2-practical-4.html#cb114-2" aria-hidden="true"></a><span class="kw">summary</span>(grp_means)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00   11.35   23.16   31.86   49.74  122.40</code></pre>
<p>A core property of the Poisson distribution is that the variance is equal to the mean. A simple diagnostic is a plot of the group variances against the group means:</p>
<ul>
<li>Poisson-distributed data will result in a linear pattern with slope = 1</li>
<li>as long as the variance is generally greater than the mean, we call the data overdispersed. Overdispersion comes in various forms:
<ul>
<li>a linear mean-variance relationship with Var = φµ (a line through the origin) with φ &gt; 1 is called a quasi-Poisson pattern (this term describes the mean-variance relationship, not any particular proability distribution); we can implement it statistically via quasilikelihood (Venables and Ripley, 2002) or by using a particular parameterization of the negative binomial distribution (“NB1” inthe terminology of Hardin and Hilbe (2007))</li>
<li>a semi-quadratic pattern, Var = µ(1 + αµ) or µ(1 + µ/k), is characteristic of overdispersed data that is driven by underlying heterogeneity among samples, either the negative binomial (gamma-Poisson) or the lognormal-Poisson <span class="citation">(Elston et al. <a href="#ref-elston2001" role="doc-biblioref">2001</a>)</span></li>
</ul></li>
</ul>
<p>We’ve already calculated the group (genotype × treatment) means, we calculate the variances in the same way.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="6.2-practical-4.html#cb116-1" aria-hidden="true"></a>grp_vars &lt;-<span class="st"> </span><span class="kw">with</span>(</span>
<span id="cb116-2"><a href="6.2-practical-4.html#cb116-2" aria-hidden="true"></a>  dat_tf,</span>
<span id="cb116-3"><a href="6.2-practical-4.html#cb116-3" aria-hidden="true"></a>  <span class="kw">tapply</span>(</span>
<span id="cb116-4"><a href="6.2-practical-4.html#cb116-4" aria-hidden="true"></a>    total.fruits,</span>
<span id="cb116-5"><a href="6.2-practical-4.html#cb116-5" aria-hidden="true"></a>    <span class="kw">list</span>(gna), var</span>
<span id="cb116-6"><a href="6.2-practical-4.html#cb116-6" aria-hidden="true"></a>  )</span>
<span id="cb116-7"><a href="6.2-practical-4.html#cb116-7" aria-hidden="true"></a>)</span></code></pre></div>
<p>We can get approximate estimates of the quasi-Poisson (linear) and negative binomial (linear/quadratic) pattern using lm.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="6.2-practical-4.html#cb117-1" aria-hidden="true"></a>lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(grp_vars <span class="op">~</span><span class="st"> </span>grp_means <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">## `quasi-Poisson&#39; fit</span></span>
<span id="cb117-2"><a href="6.2-practical-4.html#cb117-2" aria-hidden="true"></a>phi_fit &lt;-<span class="st"> </span><span class="kw">coef</span>(lm1)</span>
<span id="cb117-3"><a href="6.2-practical-4.html#cb117-3" aria-hidden="true"></a>lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>((grp_vars <span class="op">-</span><span class="st"> </span>grp_means) <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(grp_means<span class="op">^</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</span>
<span id="cb117-4"><a href="6.2-practical-4.html#cb117-4" aria-hidden="true"></a>k_fit &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="kw">coef</span>(lm2)</span></code></pre></div>
<p>Now we can plot them.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="6.2-practical-4.html#cb118-1" aria-hidden="true"></a><span class="kw">plot</span>(grp_vars <span class="op">~</span><span class="st"> </span>grp_means, <span class="dt">xlab =</span> <span class="st">&quot;group means&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;group variances&quot;</span>)</span>
<span id="cb118-2"><a href="6.2-practical-4.html#cb118-2" aria-hidden="true"></a><span class="kw">abline</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">lty =</span> <span class="dv">2</span>)</span>
<span id="cb118-3"><a href="6.2-practical-4.html#cb118-3" aria-hidden="true"></a><span class="kw">text</span>(<span class="dv">105</span>, <span class="dv">500</span>, <span class="st">&quot;Poisson&quot;</span>)</span>
<span id="cb118-4"><a href="6.2-practical-4.html#cb118-4" aria-hidden="true"></a><span class="kw">curve</span>(phi_fit <span class="op">*</span><span class="st"> </span>x, <span class="dt">col =</span> <span class="dv">2</span>, <span class="dt">add =</span> <span class="ot">TRUE</span>)</span>
<span id="cb118-5"><a href="6.2-practical-4.html#cb118-5" aria-hidden="true"></a><span class="co">## bquote() is used to substitute numeric values</span></span>
<span id="cb118-6"><a href="6.2-practical-4.html#cb118-6" aria-hidden="true"></a><span class="co">## in equations with symbols</span></span>
<span id="cb118-7"><a href="6.2-practical-4.html#cb118-7" aria-hidden="true"></a><span class="kw">text</span>(<span class="dv">110</span>, <span class="dv">3900</span>,</span>
<span id="cb118-8"><a href="6.2-practical-4.html#cb118-8" aria-hidden="true"></a>  <span class="kw">bquote</span>(<span class="kw">paste</span>(<span class="st">&quot;QP: &quot;</span>, sigma<span class="op">^</span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span>.(<span class="kw">round</span>(phi_fit, <span class="dv">1</span>)) <span class="op">*</span><span class="st"> </span>mu)),</span>
<span id="cb118-9"><a href="6.2-practical-4.html#cb118-9" aria-hidden="true"></a>  <span class="dt">col =</span> <span class="dv">2</span></span>
<span id="cb118-10"><a href="6.2-practical-4.html#cb118-10" aria-hidden="true"></a>)</span>
<span id="cb118-11"><a href="6.2-practical-4.html#cb118-11" aria-hidden="true"></a><span class="kw">curve</span>(x <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>x <span class="op">/</span><span class="st"> </span>k_fit), <span class="dt">col =</span> <span class="dv">4</span>, <span class="dt">add =</span> <span class="ot">TRUE</span>)</span>
<span id="cb118-12"><a href="6.2-practical-4.html#cb118-12" aria-hidden="true"></a><span class="kw">text</span>(<span class="dv">104</span>, <span class="dv">7200</span>, <span class="kw">paste</span>(<span class="st">&quot;NB: k=&quot;</span>, <span class="kw">round</span>(k_fit, <span class="dv">1</span>), <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>), <span class="dt">col =</span> <span class="dv">4</span>)</span>
<span id="cb118-13"><a href="6.2-practical-4.html#cb118-13" aria-hidden="true"></a>l_fit &lt;-<span class="st"> </span><span class="kw">loess</span>(grp_vars <span class="op">~</span><span class="st"> </span>grp_means)</span>
<span id="cb118-14"><a href="6.2-practical-4.html#cb118-14" aria-hidden="true"></a>mvec &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">120</span></span>
<span id="cb118-15"><a href="6.2-practical-4.html#cb118-15" aria-hidden="true"></a><span class="kw">lines</span>(mvec, <span class="kw">predict</span>(l_fit, mvec), <span class="dt">col =</span> <span class="dv">5</span>)</span>
<span id="cb118-16"><a href="6.2-practical-4.html#cb118-16" aria-hidden="true"></a><span class="kw">text</span>(<span class="dv">100</span>, <span class="dv">2500</span>, <span class="st">&quot;loess&quot;</span>, <span class="dt">col =</span> <span class="dv">5</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-63"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-63-1.svg" alt="Graphical evaluation of distribution to use" width="672" />
<p class="caption">
Figure 6.5: Graphical evaluation of distribution to use
</p>
</div>
<p>Same with ggplot</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="6.2-practical-4.html#cb119-1" aria-hidden="true"></a><span class="kw">ggplot</span>(</span>
<span id="cb119-2"><a href="6.2-practical-4.html#cb119-2" aria-hidden="true"></a>  <span class="kw">data.frame</span>(grp_means, grp_vars),</span>
<span id="cb119-3"><a href="6.2-practical-4.html#cb119-3" aria-hidden="true"></a>  <span class="kw">aes</span>(<span class="dt">x =</span> grp_means, <span class="dt">y =</span> grp_vars)) <span class="op">+</span></span>
<span id="cb119-4"><a href="6.2-practical-4.html#cb119-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb119-5"><a href="6.2-practical-4.html#cb119-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_smooth</span>(</span>
<span id="cb119-6"><a href="6.2-practical-4.html#cb119-6" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Loess&quot;</span>), <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb119-7"><a href="6.2-practical-4.html#cb119-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_smooth</span>(</span>
<span id="cb119-8"><a href="6.2-practical-4.html#cb119-8" aria-hidden="true"></a>    <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>,</span>
<span id="cb119-9"><a href="6.2-practical-4.html#cb119-9" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Q_Pois&quot;</span>)) <span class="op">+</span></span>
<span id="cb119-10"><a href="6.2-practical-4.html#cb119-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_function</span>(</span>
<span id="cb119-11"><a href="6.2-practical-4.html#cb119-11" aria-hidden="true"></a>    <span class="dt">fun =</span> <span class="cf">function</span>(x) x <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>x <span class="op">/</span><span class="st"> </span>k_fit),</span>
<span id="cb119-12"><a href="6.2-practical-4.html#cb119-12" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Neg_bin&quot;</span>)</span>
<span id="cb119-13"><a href="6.2-practical-4.html#cb119-13" aria-hidden="true"></a>  ) <span class="op">+</span></span>
<span id="cb119-14"><a href="6.2-practical-4.html#cb119-14" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_abline</span>(</span>
<span id="cb119-15"><a href="6.2-practical-4.html#cb119-15" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">colour =</span> <span class="st">&quot;Poisson&quot;</span>)) <span class="op">+</span></span>
<span id="cb119-16"><a href="6.2-practical-4.html#cb119-16" aria-hidden="true"></a><span class="st">  </span><span class="kw">scale_colour_manual</span>(</span>
<span id="cb119-17"><a href="6.2-practical-4.html#cb119-17" aria-hidden="true"></a>    <span class="dt">name =</span> <span class="st">&quot;legend&quot;</span>,</span>
<span id="cb119-18"><a href="6.2-practical-4.html#cb119-18" aria-hidden="true"></a>    <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb119-19"><a href="6.2-practical-4.html#cb119-19" aria-hidden="true"></a><span class="st">  </span><span class="kw">scale_fill_manual</span>(</span>
<span id="cb119-20"><a href="6.2-practical-4.html#cb119-20" aria-hidden="true"></a>    <span class="dt">name =</span> <span class="st">&quot;legend&quot;</span>,</span>
<span id="cb119-21"><a href="6.2-practical-4.html#cb119-21" aria-hidden="true"></a>    <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb119-22"><a href="6.2-practical-4.html#cb119-22" aria-hidden="true"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt;
## = &quot;none&quot;)` instead.</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-64"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-64-1.svg" alt="Graphical evaluation of distribution to use with ggplot" width="672" />
<p class="caption">
Figure 6.6: Graphical evaluation of distribution to use with ggplot
</p>
</div>
<!-- Todo need to edit the color legend -->
<p>These fits are not rigorous statistical tests — they violate a variety of assumptions of linear regression (e.g. constant variance, independence), but they are good enough to give us an initial guess about what distributions we should use.</p>
<p><strong>Exercise</strong></p>
<ul>
<li>compare a simple quadratic fit to the data (i.e., without the linear part) with the negative binomial and quasipoisson fits
<!-- -  Draw a plot to suggest whether one might be able to stabilize the variance of the data by log(1 + x)-transforming the data. --></li>
</ul>
<div class="exer">
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="6.2-practical-4.html#cb122-1" aria-hidden="true"></a>lm3 &lt;-<span class="st"> </span><span class="kw">lm</span>(grp_vars <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(grp_means)<span class="op">^</span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="co">## quadratic fit</span></span>
<span id="cb122-2"><a href="6.2-practical-4.html#cb122-2" aria-hidden="true"></a>quad_fit &lt;-<span class="st"> </span><span class="kw">coef</span>(lm3)</span>
<span id="cb122-3"><a href="6.2-practical-4.html#cb122-3" aria-hidden="true"></a></span>
<span id="cb122-4"><a href="6.2-practical-4.html#cb122-4" aria-hidden="true"></a><span class="kw">ggplot</span>(</span>
<span id="cb122-5"><a href="6.2-practical-4.html#cb122-5" aria-hidden="true"></a>  <span class="kw">data.frame</span>(grp_means, grp_vars),</span>
<span id="cb122-6"><a href="6.2-practical-4.html#cb122-6" aria-hidden="true"></a>  <span class="kw">aes</span>(<span class="dt">x =</span> grp_means, <span class="dt">y =</span> grp_vars)) <span class="op">+</span></span>
<span id="cb122-7"><a href="6.2-practical-4.html#cb122-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb122-8"><a href="6.2-practical-4.html#cb122-8" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_smooth</span>(</span>
<span id="cb122-9"><a href="6.2-practical-4.html#cb122-9" aria-hidden="true"></a>    <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>,</span>
<span id="cb122-10"><a href="6.2-practical-4.html#cb122-10" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Q_Pois&quot;</span>)) <span class="op">+</span></span>
<span id="cb122-11"><a href="6.2-practical-4.html#cb122-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_function</span>(</span>
<span id="cb122-12"><a href="6.2-practical-4.html#cb122-12" aria-hidden="true"></a>    <span class="dt">fun =</span> <span class="cf">function</span>(x) x <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>x <span class="op">/</span><span class="st"> </span>k_fit),</span>
<span id="cb122-13"><a href="6.2-practical-4.html#cb122-13" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Neg_bin&quot;</span>)</span>
<span id="cb122-14"><a href="6.2-practical-4.html#cb122-14" aria-hidden="true"></a>  ) <span class="op">+</span></span>
<span id="cb122-15"><a href="6.2-practical-4.html#cb122-15" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_smooth</span>(</span>
<span id="cb122-16"><a href="6.2-practical-4.html#cb122-16" aria-hidden="true"></a>    <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(x<span class="op">^</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>,</span>
<span id="cb122-17"><a href="6.2-practical-4.html#cb122-17" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">colour =</span> <span class="st">&quot;Quad&quot;</span>)) <span class="op">+</span></span>
<span id="cb122-18"><a href="6.2-practical-4.html#cb122-18" aria-hidden="true"></a><span class="st">  </span><span class="kw">scale_colour_manual</span>(</span>
<span id="cb122-19"><a href="6.2-practical-4.html#cb122-19" aria-hidden="true"></a>    <span class="dt">name =</span> <span class="st">&quot;legend&quot;</span>,</span>
<span id="cb122-20"><a href="6.2-practical-4.html#cb122-20" aria-hidden="true"></a>    <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;black&quot;</span>)) <span class="op">+</span></span>
<span id="cb122-21"><a href="6.2-practical-4.html#cb122-21" aria-hidden="true"></a><span class="st">  </span><span class="kw">scale_fill_manual</span>(</span>
<span id="cb122-22"><a href="6.2-practical-4.html#cb122-22" aria-hidden="true"></a>    <span class="dt">name =</span> <span class="st">&quot;legend&quot;</span>,</span>
<span id="cb122-23"><a href="6.2-practical-4.html#cb122-23" aria-hidden="true"></a>    <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;black&quot;</span>)) <span class="op">+</span></span>
<span id="cb122-24"><a href="6.2-practical-4.html#cb122-24" aria-hidden="true"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt;
## = &quot;none&quot;)` instead.</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-65"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-65-1.svg" alt="Graphical evaluation of distribution to use including quadratic effect" width="672" />
<p class="caption">
Figure 6.7: Graphical evaluation of distribution to use including quadratic effect
</p>
</div>
</div>
<div id="plotting-the-response-vs-treatments" class="section level4" number="6.2.5.1">
<h4><span class="header-section-number">6.2.5.1</span> Plotting the response vs treatments</h4>
<p>Just to avoid surprises</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="6.2-practical-4.html#cb124-1" aria-hidden="true"></a><span class="kw">ggplot</span>(dat_tf, <span class="kw">aes</span>(<span class="dt">x =</span> amd, <span class="dt">y =</span> <span class="kw">log</span>(total.fruits <span class="op">+</span><span class="st"> </span><span class="dv">1</span>), <span class="dt">colour =</span> nutrient)) <span class="op">+</span></span>
<span id="cb124-2"><a href="6.2-practical-4.html#cb124-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb124-3"><a href="6.2-practical-4.html#cb124-3" aria-hidden="true"></a><span class="st">  </span><span class="co">## need to use as.numeric(amd) to get lines</span></span>
<span id="cb124-4"><a href="6.2-practical-4.html#cb124-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.numeric</span>(amd)), <span class="dt">fun =</span> mean, <span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>) <span class="op">+</span></span>
<span id="cb124-5"><a href="6.2-practical-4.html#cb124-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb124-6"><a href="6.2-practical-4.html#cb124-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.spacing =</span> <span class="kw">unit</span>(<span class="dv">0</span>, <span class="st">&quot;lines&quot;</span>)) <span class="op">+</span></span>
<span id="cb124-7"><a href="6.2-practical-4.html#cb124-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>popu)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-66"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-66-1.svg" alt="Fruit production by treatments by population" width="672" />
<p class="caption">
Figure 6.8: Fruit production by treatments by population
</p>
</div>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="6.2-practical-4.html#cb125-1" aria-hidden="true"></a><span class="kw">ggplot</span>(dat_tf, <span class="kw">aes</span>(<span class="dt">x =</span> amd, <span class="dt">y =</span> <span class="kw">log</span>(total.fruits <span class="op">+</span><span class="st"> </span><span class="dv">1</span>), <span class="dt">colour =</span> gen)) <span class="op">+</span></span>
<span id="cb125-2"><a href="6.2-practical-4.html#cb125-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb125-3"><a href="6.2-practical-4.html#cb125-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.numeric</span>(amd)), <span class="dt">fun =</span> mean, <span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>) <span class="op">+</span></span>
<span id="cb125-4"><a href="6.2-practical-4.html#cb125-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb125-5"><a href="6.2-practical-4.html#cb125-5" aria-hidden="true"></a><span class="st">  </span><span class="co">## label_both adds variable name (&#39;nutrient&#39;) to facet labels</span></span>
<span id="cb125-6"><a href="6.2-practical-4.html#cb125-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>nutrient, <span class="dt">labeller =</span> label_both)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-67"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-67-1.svg" alt="Fruit production by genotype by treatments" width="672" />
<p class="caption">
Figure 6.9: Fruit production by genotype by treatments
</p>
</div>
</div>
</div>
<div id="fitting-group-wise-glm" class="section level3" number="6.2.6">
<h3><span class="header-section-number">6.2.6</span> Fitting group-wise GLM</h3>
<p>Another general starting approach is to fit GLMs to each group of data separately, equivalent to treating the grouping variables as fixed effects.
This should result in reasonable variation among treatment effects. We first fit the models, and then examine the coefficients.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="6.2-practical-4.html#cb126-1" aria-hidden="true"></a>glm_lis &lt;-<span class="st"> </span><span class="kw">lmList</span>(</span>
<span id="cb126-2"><a href="6.2-practical-4.html#cb126-2" aria-hidden="true"></a>  total.fruits <span class="op">~</span><span class="st"> </span>nutrient <span class="op">*</span><span class="st"> </span>amd <span class="op">|</span><span class="st"> </span>gen,</span>
<span id="cb126-3"><a href="6.2-practical-4.html#cb126-3" aria-hidden="true"></a>  <span class="dt">data =</span> dat_tf,</span>
<span id="cb126-4"><a href="6.2-practical-4.html#cb126-4" aria-hidden="true"></a>  <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb126-5"><a href="6.2-practical-4.html#cb126-5" aria-hidden="true"></a><span class="kw">plot.lmList</span>(glm_lis)</span></code></pre></div>
<pre><code>## Using grp as id variables</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-68"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-68-1.svg" alt="Model coefficients for GLM fits on each genotype" width="672" />
<p class="caption">
Figure 6.10: Model coefficients for GLM fits on each genotype
</p>
</div>
<p>Three genotypes (5, 6, 34) have extreme coefficients (Fig. 5). A mixed model assumes that the underlying random effects are normally distributed, although we shouldn’t take these outliers too seriously at this point — we are not actually plotting the random effects, or even estimates of random effects (which are not themselves guaranteed to be normally distributed), but rather separate estimates for each group.
Create a plotting function for Q-Q plots of these coefficients to visualize the departure from normality.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="6.2-practical-4.html#cb128-1" aria-hidden="true"></a><span class="kw">qqmath.lmList</span>(glm_lis)</span></code></pre></div>
<pre><code>## Using  as id variables</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-69"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-69-1.svg" alt="Q-Q plots of model coefficients for GLM fits on each genotype" width="672" />
<p class="caption">
Figure 6.11: Q-Q plots of model coefficients for GLM fits on each genotype
</p>
</div>
<p>We see that these extreme coefficients fall far outside a normal error distribution. We shouldn’t take these outliers too seriously at this point — we are not actually plotting the random effects, or even estimates of random effects, but rather separate estimates for each group.
Especially if these groups have relatively small sample sizes, the estimates may eventually be “shrunk” closer to the mean when we do the mixed model.
We should nonetheless take care to see if the coefficients for these genotypes from the GLMM are still outliers, and take the same precautions as we usually do for outliers. For example, we can look back at the original data to see if there is something weird about the way those genotypes were collected, or try re-running the analysis without those genotypes to see if the results are robust.</p>
</div>
<div id="fitting-and-evaluating-glmms" class="section level3" number="6.2.7">
<h3><span class="header-section-number">6.2.7</span> Fitting and evaluating GLMMs</h3>
<p>Now we (try to) build and fit a full model, using <code>glmer</code> in the <code>emo::ji("pacakage")</code> <code>lme4</code>. This model has random effects for all genotype and population × treatment random effects, and for the nuisance variables for the rack and germination method (status). (Given the mean-variance relationship we saw it’s pretty clear that we are going to have to proceed eventually to a model with overdispersion, but we fit the Poisson model first for illustration.)</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="6.2-practical-4.html#cb130-1" aria-hidden="true"></a>mp1 &lt;-<span class="st"> </span><span class="kw">glmer</span>(total.fruits <span class="op">~</span><span class="st"> </span>nutrient <span class="op">*</span><span class="st"> </span>amd <span class="op">+</span></span>
<span id="cb130-2"><a href="6.2-practical-4.html#cb130-2" aria-hidden="true"></a><span class="st">  </span>rack <span class="op">+</span><span class="st"> </span>status <span class="op">+</span></span>
<span id="cb130-3"><a href="6.2-practical-4.html#cb130-3" aria-hidden="true"></a><span class="st">  </span>(amd <span class="op">*</span><span class="st"> </span>nutrient <span class="op">|</span><span class="st"> </span>popu) <span class="op">+</span></span>
<span id="cb130-4"><a href="6.2-practical-4.html#cb130-4" aria-hidden="true"></a><span class="st">  </span>(amd <span class="op">*</span><span class="st"> </span>nutrient <span class="op">|</span><span class="st"> </span>gen),</span>
<span id="cb130-5"><a href="6.2-practical-4.html#cb130-5" aria-hidden="true"></a><span class="dt">data =</span> dat_tf, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span></span>
<span id="cb130-6"><a href="6.2-practical-4.html#cb130-6" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.00550538
## (tol = 0.002, component 1)</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="6.2-practical-4.html#cb132-1" aria-hidden="true"></a><span class="kw">overdisp_fun</span>(mp1)</span></code></pre></div>
<pre><code>##       chisq       ratio           p 
## 13909.46583    23.25998     0.00000</code></pre>
<!-- add description of the overdispersion function -->
<p>The <code>overdisp_fun()</code> is described [here] <a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#testing-for-overdispersioncomputing-overdispersion-factor" class="uri">https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#testing-for-overdispersioncomputing-overdispersion-factor</a>) on the absolutely fantastic FAQ about GLMMs by Ben Bolker <a href="https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html" class="uri">https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html</a></p>
<p>We can ignore the model convergence for the moment. This shows that the data are (extremely) over-dispersed, given the model.</p>
<p>We can also use the excellent <code>DHARMa</code> 📦 <span class="citation">(Hartig <a href="#ref-R-DHARMa" role="doc-biblioref">2022</a>)</span> to evaluate fit of <em>glm</em> and <em>glmm</em>. So instead of using the function <code>overdisp_fun()</code>, we can simply use the function <code>testDispersion()</code>.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="6.2-practical-4.html#cb134-1" aria-hidden="true"></a><span class="kw">testDispersion</span>(mp1)</span></code></pre></div>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-71-1.svg" width="672" /></p>
<pre><code>## 
##  DHARMa nonparametric dispersion test via sd of residuals fitted vs.
##  simulated
## 
## data:  simulationOutput
## dispersion = 1.2906, p-value = 0.392
## alternative hypothesis: two.sided</code></pre>
<p>As you can see, DHARMa suggests that there is no overdispersion based on the distribution of residuals from simulated data. We are going to consider that we have overdispersion and adjust the model accordingly.</p>
<p>Now we add the observation-level random effect to the model to account for overdispersion <span class="citation">(Elston et al. <a href="#ref-elston2001" role="doc-biblioref">2001</a>)</span>.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="6.2-practical-4.html#cb136-1" aria-hidden="true"></a>mp2 &lt;-<span class="st"> </span><span class="kw">update</span>(mp1, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>X))</span></code></pre></div>
<pre><code>## Warning in (function (fn, par, lower = rep.int(-Inf, n), upper =
## rep.int(Inf, : failure to converge in 10000 evaluations</code></pre>
<pre><code>## Warning in optwrap(optimizer, devfun, start, rho$lower, control = control, :
## convergence code 4 from Nelder_Mead: failure to converge in 10000 evaluations</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.0864843 (tol
## = 0.002, component 1)</code></pre>
<p>The model takes much longer to fit (and gives warnings).
We look just at the variance components. In particular, if we look at the correlation matrix among the genotype random effects, we see a perfect
correlation.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="6.2-practical-4.html#cb140-1" aria-hidden="true"></a><span class="kw">attr</span>(<span class="kw">VarCorr</span>(mp2)<span class="op">$</span>gen, <span class="st">&quot;correlation&quot;</span>)</span></code></pre></div>
<pre><code>##                         (Intercept) amdclipped nutrientHigh
## (Intercept)               1.0000000 -0.9938107   -0.9874693
## amdclipped               -0.9938107  1.0000000    0.9848999
## nutrientHigh             -0.9874693  0.9848999    1.0000000
## amdclipped:nutrientHigh   0.8295187 -0.8383845   -0.9072315
##                         amdclipped:nutrientHigh
## (Intercept)                           0.8295187
## amdclipped                           -0.8383845
## nutrientHigh                         -0.9072315
## amdclipped:nutrientHigh               1.0000000</code></pre>
<p>We’ll try getting rid of the correlations between clipping (<code>amd</code>) and nutrients, using <code>amd+nutrient</code> instead of <code>amd*nutrient</code> in the random effects specification (here it seems easier to re-do the model rather than using update to add and subtract terms).</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="6.2-practical-4.html#cb142-1" aria-hidden="true"></a>mp3 &lt;-<span class="st"> </span><span class="kw">glmer</span>(total.fruits <span class="op">~</span><span class="st"> </span>nutrient <span class="op">*</span><span class="st"> </span>amd <span class="op">+</span></span>
<span id="cb142-2"><a href="6.2-practical-4.html#cb142-2" aria-hidden="true"></a><span class="st">  </span>rack <span class="op">+</span><span class="st"> </span>status <span class="op">+</span></span>
<span id="cb142-3"><a href="6.2-practical-4.html#cb142-3" aria-hidden="true"></a><span class="st">  </span>(amd <span class="op">+</span><span class="st"> </span>nutrient <span class="op">|</span><span class="st"> </span>popu) <span class="op">+</span></span>
<span id="cb142-4"><a href="6.2-practical-4.html#cb142-4" aria-hidden="true"></a><span class="st">  </span>(amd <span class="op">+</span><span class="st"> </span>nutrient <span class="op">|</span><span class="st"> </span>gen) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>X),</span>
<span id="cb142-5"><a href="6.2-practical-4.html#cb142-5" aria-hidden="true"></a><span class="dt">data =</span> dat_tf, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span></span>
<span id="cb142-6"><a href="6.2-practical-4.html#cb142-6" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="6.2-practical-4.html#cb144-1" aria-hidden="true"></a><span class="kw">attr</span>(<span class="kw">VarCorr</span>(mp3)<span class="op">$</span>gen, <span class="st">&quot;correlation&quot;</span>)</span></code></pre></div>
<pre><code>##              (Intercept) amdclipped nutrientHigh
## (Intercept)    1.0000000 -0.9999990   -0.9974329
## amdclipped    -0.9999990  1.0000000    0.9974626
## nutrientHigh  -0.9974329  0.9974626    1.0000000</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="6.2-practical-4.html#cb146-1" aria-hidden="true"></a><span class="kw">attr</span>(<span class="kw">VarCorr</span>(mp3)<span class="op">$</span>popu, <span class="st">&quot;correlation&quot;</span>)</span></code></pre></div>
<pre><code>##              (Intercept) amdclipped nutrientHigh
## (Intercept)    1.0000000  0.9938305    0.9985769
## amdclipped     0.9938305  1.0000000    0.9884101
## nutrientHigh   0.9985769  0.9884101    1.0000000</code></pre>
<p>Unfortunately, we still have perfect correlations among the random effects terms. For some models (e.g. random-slope models), it is possible to fit random effects models in such a way that the correlation between the different parameters (intercept and slope in the case of random-slope models) is constrained to be zero, by fitting a model like <code>(1|f)+(0+x|f)</code>; unfortunately, because of the way lme4 is set up, this is considerably more difficult with categorical predictors (factors).</p>
<p>We have to reduce the model further in some way in order not to overfit (i.e., in order to not have perfect ±1 correlations among random effects). It looks like we can’t allow both nutrients and clipping in the random effect model at either the population or the genotype level. However, it’s hard to know whether we should proceed with amd or nutrient, both, or neither in the model.</p>
<p>A convenient way to proceed if we are going to try fitting several different combinations of random effects is to fit the model with all the fixed effects but only observation-level random effects, and then to use update to add various components to it.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="6.2-practical-4.html#cb148-1" aria-hidden="true"></a>mp_obs &lt;-<span class="st"> </span><span class="kw">glmer</span>(total.fruits <span class="op">~</span><span class="st"> </span>nutrient <span class="op">*</span><span class="st"> </span>amd <span class="op">+</span></span>
<span id="cb148-2"><a href="6.2-practical-4.html#cb148-2" aria-hidden="true"></a><span class="st">  </span>rack <span class="op">+</span><span class="st"> </span>status <span class="op">+</span></span>
<span id="cb148-3"><a href="6.2-practical-4.html#cb148-3" aria-hidden="true"></a><span class="st">  </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>X),</span>
<span id="cb148-4"><a href="6.2-practical-4.html#cb148-4" aria-hidden="true"></a><span class="dt">data =</span> dat_tf, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span></span>
<span id="cb148-5"><a href="6.2-practical-4.html#cb148-5" aria-hidden="true"></a>)</span></code></pre></div>
<p>Now, for example, <code>update(mp_obs,.~.+(1|gen)+(amd|popu))</code> fits the model with intercept random effects at the genotype level and variation in clipping effects across populations.</p>

<div class="rmdcode">
<p><strong>Exercise</strong> using update, fit the models with</p>
<ol style="list-style-type: decimal">
<li>clipping variation at both genotype and population levels;</li>
<li>nutrient variation at both genotype and populations; convince yourself that trying to fit variation in either clipping or nutrients leads to overfitting (perfect correlations).</li>
<li>Fit the model with only intercept variation at the population and genotype levels, saving it as mp4; show that there is non-zero variance estimated</li>
</ol>
</div>
<div class="exer">
<ol style="list-style-type: decimal">
<li></li>
</ol>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="6.2-practical-4.html#cb149-1" aria-hidden="true"></a>mpcli &lt;-<span class="st"> </span><span class="kw">update</span>(mp_obs, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(amd <span class="op">|</span><span class="st"> </span>gen) <span class="op">+</span><span class="st"> </span>(amd <span class="op">|</span><span class="st"> </span>popu))</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.0971186 (tol
## = 0.002, component 1)</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="6.2-practical-4.html#cb151-1" aria-hidden="true"></a><span class="kw">VarCorr</span>(mpcli)</span></code></pre></div>
<pre><code>##  Groups Name        Std.Dev. Corr  
##  X      (Intercept) 1.431030       
##  gen    (Intercept) 0.296668       
##         amdclipped  0.040105 -0.855
##  popu   (Intercept) 0.751957       
##         amdclipped  0.129003 0.996</code></pre>
<ol start="2" style="list-style-type: decimal">
<li></li>
</ol>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="6.2-practical-4.html#cb153-1" aria-hidden="true"></a>mpnut &lt;-<span class="st"> </span><span class="kw">update</span>(mp_obs, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(nutrient <span class="op">|</span><span class="st"> </span>gen) <span class="op">+</span><span class="st"> </span>(nutrient <span class="op">|</span><span class="st"> </span>popu))</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.0229913 (tol
## = 0.002, component 1)</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="6.2-practical-4.html#cb155-1" aria-hidden="true"></a><span class="kw">VarCorr</span>(mpnut)</span></code></pre></div>
<pre><code>##  Groups Name         Std.Dev. Corr  
##  X      (Intercept)  1.41950        
##  gen    (Intercept)  0.47815        
##         nutrientHigh 0.32489  -1.000
##  popu   (Intercept)  0.74336        
##         nutrientHigh 0.11974  1.000</code></pre>
<ol start="3" style="list-style-type: decimal">
<li></li>
</ol>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="6.2-practical-4.html#cb157-1" aria-hidden="true"></a>mp4 &lt;-<span class="st"> </span><span class="kw">update</span>(mp_obs, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>gen) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>popu))</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.00335685
## (tol = 0.002, component 1)</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="6.2-practical-4.html#cb159-1" aria-hidden="true"></a><span class="kw">VarCorr</span>(mp4)</span></code></pre></div>
<pre><code>##  Groups Name        Std.Dev.
##  X      (Intercept) 1.43133 
##  gen    (Intercept) 0.28586 
##  popu   (Intercept) 0.80553</code></pre>
</div>
<p>In other words, while it’s biologically plausible that there is some variation in the nutrient or clipping effect at the genotype or population levels, with this modeling approach we really don’t have enough data to speak confidently about these effects.
Let’s check that mp4 no longer incorporates overdispersion (the observationlevel random effect should have taken care of it):</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="6.2-practical-4.html#cb161-1" aria-hidden="true"></a><span class="kw">overdisp_fun</span>(mp4)</span></code></pre></div>
<pre><code>##       chisq       ratio           p 
## 177.5133664   0.2886396   1.0000000</code></pre>
<p>Using the <code>DHARMa</code> 📦, we will also check the model. To do so we first need to simulate some data and get the <em>scaled residuals</em> following the DHARMa notation.
Then we can check the distributional properties of the <em>scaled residuals</em> and see if they follow the classic assumption using the different functions provided.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="6.2-practical-4.html#cb163-1" aria-hidden="true"></a>scaled_res &lt;-<span class="st"> </span><span class="kw">simulateResiduals</span>(mp4)</span>
<span id="cb163-2"><a href="6.2-practical-4.html#cb163-2" aria-hidden="true"></a><span class="kw">plot</span>(scaled_res)</span></code></pre></div>
<pre><code>## DHARMa:testOutliers with type = binomial may have inflated Type I error rates for integer-valued distributions. To get a more exact result, it is recommended to re-run testOutliers with type = &#39;bootstrap&#39;. See ?testOutliers for details</code></pre>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-81-1.svg" width="672" /></p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="6.2-practical-4.html#cb165-1" aria-hidden="true"></a><span class="kw">testZeroInflation</span>(mp4, <span class="dt">plot =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-81-2.svg" width="672" /></p>
<pre><code>## 
##  DHARMa zero-inflation test via comparison to expected zeros with
##  simulation under H0 = fitted model
## 
## data:  simulationOutput
## ratioObsSim = 1.9799, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="6.2-practical-4.html#cb167-1" aria-hidden="true"></a><span class="co"># note about overdispersion</span></span>
<span id="cb167-2"><a href="6.2-practical-4.html#cb167-2" aria-hidden="true"></a><span class="kw">sum</span>(dat_tf<span class="op">$</span>total.fruits <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 126</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="6.2-practical-4.html#cb169-1" aria-hidden="true"></a>a &lt;-<span class="st"> </span><span class="kw">predict</span>(mp4, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb169-2"><a href="6.2-practical-4.html#cb169-2" aria-hidden="true"></a>b &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">500</span>)</span>
<span id="cb169-3"><a href="6.2-practical-4.html#cb169-3" aria-hidden="true"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">500</span>) {</span>
<span id="cb169-4"><a href="6.2-practical-4.html#cb169-4" aria-hidden="true"></a>  b[j] &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">sapply</span>(<span class="kw">seq</span>(<span class="kw">nrow</span>(dat_tf)), <span class="cf">function</span>(i) <span class="kw">rpois</span>(<span class="dv">1</span>, a[i])) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</span>
<span id="cb169-5"><a href="6.2-practical-4.html#cb169-5" aria-hidden="true"></a>}</span>
<span id="cb169-6"><a href="6.2-practical-4.html#cb169-6" aria-hidden="true"></a><span class="kw">hist</span>(b)</span></code></pre></div>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-82-1.svg" width="672" /></p>
</div>
<div id="inference" class="section level3" number="6.2.8">
<h3><span class="header-section-number">6.2.8</span> Inference</h3>
<div id="random-effects" class="section level4" number="6.2.8.1">
<h4><span class="header-section-number">6.2.8.1</span> Random effects</h4>
<p><code>glmer</code> (<code>lmer</code>) does not return information about the standard errors or confidence intervals of the variance components.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="6.2-practical-4.html#cb170-1" aria-hidden="true"></a><span class="kw">VarCorr</span>(mp4)</span></code></pre></div>
<pre><code>##  Groups Name        Std.Dev.
##  X      (Intercept) 1.43133 
##  gen    (Intercept) 0.28586 
##  popu   (Intercept) 0.80553</code></pre>
<div id="testing-for-random-effects-1" class="section level5" number="6.2.8.1.1">
<h5><span class="header-section-number">6.2.8.1.1</span> Testing for random Effects</h5>
<p>If we want to test the significance of the random effects we can fit reduced models and run likelihood ratio tests via anova, keeping in mind that in this case (testing a null hypothesis of zero variance, where the parameter is on the boundary of its feasible region) the reported p value is approximately twice what it should be.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="6.2-practical-4.html#cb172-1" aria-hidden="true"></a>mp4v1 &lt;-<span class="st"> </span><span class="kw">update</span>(mp_obs, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>popu)) <span class="co">## popu only (drop gen)</span></span>
<span id="cb172-2"><a href="6.2-practical-4.html#cb172-2" aria-hidden="true"></a>mp4v2 &lt;-<span class="st"> </span><span class="kw">update</span>(mp_obs, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>gen)) <span class="co">## gen only (drop popu)</span></span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl =
## control$checkConv, : Model failed to converge with max|grad| = 0.105093 (tol
## = 0.002, component 1)</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
##  - Rescale variables?</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="6.2-practical-4.html#cb175-1" aria-hidden="true"></a><span class="kw">anova</span>(mp4, mp4v1)</span></code></pre></div>
<pre><code>## Data: dat_tf
## Models:
## mp4v1: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | popu) + nutrient:amd
## mp4: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | gen) + (1 | popu) + nutrient:amd
##       npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)  
## mp4v1    9 5017.4 5057.4 -2499.7   4999.4                       
## mp4     10 5015.4 5059.8 -2497.7   4995.4 4.0638  1    0.04381 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="6.2-practical-4.html#cb177-1" aria-hidden="true"></a><span class="kw">anova</span>(mp4, mp4v2)</span></code></pre></div>
<pre><code>## Data: dat_tf
## Models:
## mp4v2: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | gen) + nutrient:amd
## mp4: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | gen) + (1 | popu) + nutrient:amd
##       npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
## mp4v2    9 5031.6 5071.5 -2506.8   5013.6                         
## mp4     10 5015.4 5059.8 -2497.7   4995.4 18.212  1  1.976e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>For various forms of linear mixed models, the RLRsim package can do efficient simulation-based hypothesis testing of variance components — un- fortunately, that doesn’t include GLMMs.
If we are sufficiently patient we can do hypothesis testing via brute-force parametric bootstrapping where we repeatedly simulate data from the reduced (null) model, fit both the re- duced and full models to the simulated data, and compute the distribution of the deviance (change in -2 log likelihood).
The code below took about half an hour on a reasonably modern desktop computer.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="6.2-practical-4.html#cb179-1" aria-hidden="true"></a>simdev &lt;-<span class="st"> </span><span class="cf">function</span>() {</span>
<span id="cb179-2"><a href="6.2-practical-4.html#cb179-2" aria-hidden="true"></a>  newdat &lt;-<span class="st"> </span><span class="kw">simulate</span>(mp4v1)</span>
<span id="cb179-3"><a href="6.2-practical-4.html#cb179-3" aria-hidden="true"></a>  reduced &lt;-<span class="st"> </span>lme4<span class="op">::</span><span class="kw">refit</span>(mp4v1, newdat)</span>
<span id="cb179-4"><a href="6.2-practical-4.html#cb179-4" aria-hidden="true"></a>  full &lt;-<span class="st"> </span>lme4<span class="op">::</span><span class="kw">refit</span>(mp4, newdat)</span>
<span id="cb179-5"><a href="6.2-practical-4.html#cb179-5" aria-hidden="true"></a>  <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">c</span>(<span class="kw">logLik</span>(full) <span class="op">-</span><span class="st"> </span><span class="kw">logLik</span>(reduced)))</span>
<span id="cb179-6"><a href="6.2-practical-4.html#cb179-6" aria-hidden="true"></a>}</span>
<span id="cb179-7"><a href="6.2-practical-4.html#cb179-7" aria-hidden="true"></a></span>
<span id="cb179-8"><a href="6.2-practical-4.html#cb179-8" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb179-9"><a href="6.2-practical-4.html#cb179-9" aria-hidden="true"></a>nulldist0 &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">2</span>, <span class="kw">simdev</span>())</span>
<span id="cb179-10"><a href="6.2-practical-4.html#cb179-10" aria-hidden="true"></a><span class="co">## zero spurious (small) negative values</span></span>
<span id="cb179-11"><a href="6.2-practical-4.html#cb179-11" aria-hidden="true"></a>nulldist[nulldist <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw">abs</span>(nulldist) <span class="op">&lt;</span><span class="st"> </span><span class="fl">1e-5</span>] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb179-12"><a href="6.2-practical-4.html#cb179-12" aria-hidden="true"></a>obsdev &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">c</span>(<span class="kw">logLik</span>(mp4) <span class="op">-</span><span class="st"> </span><span class="kw">logLik</span>(mp4v1))</span></code></pre></div>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="6.2-practical-4.html#cb180-1" aria-hidden="true"></a><span class="kw">mean</span>(<span class="kw">c</span>(nulldist, obsdev) <span class="op">&gt;=</span><span class="st"> </span>obsdev)</span></code></pre></div>
<pre><code>## [1] 0.01492537</code></pre>
<p>The true p-value is actually closer to 0.05 than 0.02. In other words, here the deviations from the original statistical model from that for which the original “p value is inflated by 2” rule of thumb was derived — fitting a GLMM instead of a LMM, and using a moderate-sized rather than an arbitrarily large (asymptotic) data set — have made the likelihood ratio test liberal (increased type I error) rather than conservative (decreased type I error).</p>
<p>We can also inspect the random effects estimates themselves (in proper statistical jargon, these might be considered “predictions” rather than “estimates” (Robinson, 1991)). We use the built-in dotplot method for the random effects extracted from glmer fits (i.e. ranef(model,condVar=TRUE)), which returns a list of plots, one for each random effect level in the model.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="6.2-practical-4.html#cb182-1" aria-hidden="true"></a>r1 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">ranef</span>(mp4, <span class="dt">condVar =</span> <span class="ot">TRUE</span>, <span class="dt">whichel =</span> <span class="kw">c</span>(<span class="st">&quot;gen&quot;</span>, <span class="st">&quot;popu&quot;</span>)))</span>
<span id="cb182-2"><a href="6.2-practical-4.html#cb182-2" aria-hidden="true"></a>p1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">subset</span>(r1, grpvar <span class="op">==</span><span class="st"> &quot;gen&quot;</span>), <span class="kw">aes</span>(<span class="dt">y =</span> grp, <span class="dt">x =</span> condval)) <span class="op">+</span></span>
<span id="cb182-3"><a href="6.2-practical-4.html#cb182-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb182-4"><a href="6.2-practical-4.html#cb182-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_pointrange</span>(</span>
<span id="cb182-5"><a href="6.2-practical-4.html#cb182-5" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">xmin =</span> condval <span class="op">-</span><span class="st"> </span>condsd <span class="op">*</span><span class="st"> </span><span class="fl">1.96</span>, <span class="dt">xmax =</span> condval <span class="op">+</span><span class="st"> </span>condsd <span class="op">*</span><span class="st"> </span><span class="fl">1.96</span>)</span>
<span id="cb182-6"><a href="6.2-practical-4.html#cb182-6" aria-hidden="true"></a>  ) <span class="op">+</span></span>
<span id="cb182-7"><a href="6.2-practical-4.html#cb182-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb182-8"><a href="6.2-practical-4.html#cb182-8" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></span>
<span id="cb182-9"><a href="6.2-practical-4.html#cb182-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb182-10"><a href="6.2-practical-4.html#cb182-10" aria-hidden="true"></a>p2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">subset</span>(r1, grpvar <span class="op">==</span><span class="st"> &quot;popu&quot;</span>), <span class="kw">aes</span>(<span class="dt">y =</span> grp, <span class="dt">x =</span> condval)) <span class="op">+</span></span>
<span id="cb182-11"><a href="6.2-practical-4.html#cb182-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb182-12"><a href="6.2-practical-4.html#cb182-12" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_pointrange</span>(</span>
<span id="cb182-13"><a href="6.2-practical-4.html#cb182-13" aria-hidden="true"></a>    <span class="kw">aes</span>(<span class="dt">xmin =</span> condval <span class="op">-</span><span class="st"> </span>condsd <span class="op">*</span><span class="st"> </span><span class="fl">1.96</span>, <span class="dt">xmax =</span> condval <span class="op">+</span><span class="st"> </span>condsd <span class="op">*</span><span class="st"> </span><span class="fl">1.96</span>)</span>
<span id="cb182-14"><a href="6.2-practical-4.html#cb182-14" aria-hidden="true"></a>  ) <span class="op">+</span></span>
<span id="cb182-15"><a href="6.2-practical-4.html#cb182-15" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb182-16"><a href="6.2-practical-4.html#cb182-16" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></span>
<span id="cb182-17"><a href="6.2-practical-4.html#cb182-17" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb182-18"><a href="6.2-practical-4.html#cb182-18" aria-hidden="true"></a>p1 <span class="op">+</span><span class="st"> </span>p2</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-87"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-87-1.svg" alt="Distribution of BLUPs for genotypes and populations" width="672" />
<p class="caption">
Figure 6.12: Distribution of BLUPs for genotypes and populations
</p>
</div>
<p>As expected from the similarity of the variance estimates, the population-level estimates (the only shared component) do not differ much between the two models. There is a hint of regional differentiation — the Spanish populations have higher fruit sets than the Swedish and Dutch populations. Genotype 34 again looks a little bit unusual.</p>
</div>
</div>
<div id="fixed-effects" class="section level4" number="6.2.8.2">
<h4><span class="header-section-number">6.2.8.2</span> Fixed effects</h4>
<p>Now we want to do inference on the fixed effects. We use the drop1 func- tion to assess both the AIC difference and the likelihood ratio test between models. (In glmm_funs.R we define a convenience function dfun to convert the AIC tables returned by drop1 (which we will create momentarily) into ∆AIC tables.) Although the likelihood ratio test (and the AIC) are asymptotic tests, comparing fits between full and reduced models is still more accurate than the Wald (curvature-based) tests shown in the summary tables for glmer fits.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="6.2-practical-4.html#cb183-1" aria-hidden="true"></a>(dd_aic &lt;-<span class="st"> </span><span class="kw">dfun</span>(<span class="kw">drop1</span>(mp4)))</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | 
##     gen) + (1 | popu) + nutrient:amd
##              npar   dAIC
## &lt;none&gt;             0.000
## rack            1 55.083
## status          2  1.612
## nutrient:amd    1  1.444</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="6.2-practical-4.html#cb185-1" aria-hidden="true"></a>(dd_lrt &lt;-<span class="st"> </span><span class="kw">drop1</span>(mp4, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>))</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | 
##     gen) + (1 | popu) + nutrient:amd
##              npar    AIC    LRT   Pr(Chi)    
## &lt;none&gt;            5015.4                     
## rack            1 5070.5 57.083 4.179e-14 ***
## status          2 5017.0  5.612   0.06044 .  
## nutrient:amd    1 5016.8  3.444   0.06349 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>On the basis of these comparisons, there appears to be a very strong effect of rack and weak effects of status and of the interaction term. Dropping the nutrient:amd interaction gives a (slightly) increased AIC (∆AIC = 1.4), so the full model has the best expected predictive capability (by a small margin). On the other hand, the p-value is slightly above 0.05 (p = 0.06). At this point we remove the non-significant interaction term so we can test the main effects. (We don’t worry about removing status because it measures an aspect of experimental design that we want to leave in the model whether it is significant or not.) Once we have fitted the reduced model, we can run the LRT via anova.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="6.2-practical-4.html#cb187-1" aria-hidden="true"></a>mp5 &lt;-<span class="st"> </span><span class="kw">update</span>(mp4, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>amd<span class="op">:</span>nutrient)</span>
<span id="cb187-2"><a href="6.2-practical-4.html#cb187-2" aria-hidden="true"></a><span class="kw">anova</span>(mp5, mp4)</span></code></pre></div>
<pre><code>## Data: dat_tf
## Models:
## mp5: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | gen) + (1 | popu)
## mp4: total.fruits ~ nutrient + amd + rack + status + (1 | X) + (1 | gen) + (1 | popu) + nutrient:amd
##     npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)  
## mp5    9 5016.8 5056.8 -2499.4   4998.8                       
## mp4   10 5015.4 5059.8 -2497.7   4995.4 3.4438  1    0.06349 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Exercise</strong>
Test now the reduced model.</p>
<p>In the reduced model, we find that both nutrients and clipping have strong effects, whether measured by AIC or LRT. If we wanted to be still more careful about our interpretation, we would try to relax the asymptotic assumption. In classical linear models, we would do this by doing F tests with the appropriate denominator degrees of freedom. In “modern” mixed model approaches, we might try to use denominator-degree-of-freedom approximations such as the Kenward-Roger (despite the controversy over these approximations, they are actually available in <code>lmerTest</code>, but they do not apply to GLMMs. We can use a parametric bootstrap comparison between nested models to test fixed effects, as we did above for random effects, with the caveat that is computationally slow.</p>
<p>In addition, we can check the normality of the random effects and find they are reasonable (Fig. 10).</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="6.2-practical-4.html#cb189-1" aria-hidden="true"></a>r5 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">ranef</span>(mp5))</span>
<span id="cb189-2"><a href="6.2-practical-4.html#cb189-2" aria-hidden="true"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> r5, <span class="kw">aes</span>(<span class="dt">sample =</span> condval)) <span class="op">+</span></span>
<span id="cb189-3"><a href="6.2-practical-4.html#cb189-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_qq_line</span>() <span class="op">+</span></span>
<span id="cb189-4"><a href="6.2-practical-4.html#cb189-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>grpvar) <span class="op">+</span></span>
<span id="cb189-5"><a href="6.2-practical-4.html#cb189-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-90"></span>
<img src="BIO8940_book_files/figure-html/unnamed-chunk-90-1.svg" alt="Q-Q plot of BLUPs from model mp5" width="672" />
<p class="caption">
Figure 6.13: Q-Q plot of BLUPs from model mp5
</p>
</div>
<p>Checking everything with DHARMa also</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="6.2-practical-4.html#cb190-1" aria-hidden="true"></a>scaled_res &lt;-<span class="st"> </span><span class="kw">simulateResiduals</span>(mp5)</span>
<span id="cb190-2"><a href="6.2-practical-4.html#cb190-2" aria-hidden="true"></a><span class="kw">plot</span>(scaled_res)</span></code></pre></div>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-91-1.svg" width="672" /></p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="6.2-practical-4.html#cb191-1" aria-hidden="true"></a><span class="kw">testZeroInflation</span>(mp5, <span class="dt">plot =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="BIO8940_book_files/figure-html/unnamed-chunk-91-2.svg" width="672" /></p>
<pre><code>## 
##  DHARMa zero-inflation test via comparison to expected zeros with
##  simulation under H0 = fitted model
## 
## data:  simulationOutput
## ratioObsSim = 1.9783, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
<p>It is better than before but not perfect. I think this is completely OK and that it will extremely rarely be perfect. You need to learn what is acceptable (by that I mean you find acceptable) and be happy to justify and discuss your decisions.</p>
</div>
</div>
<div id="conclusions" class="section level3" number="6.2.9">
<h3><span class="header-section-number">6.2.9</span> Conclusions</h3>
<p>Our final model includes fixed effects of nutrients and clipping, as well as the nuisance variables rack and status; observation-level random effects to ac- count for overdispersion; and variation in overall fruit set at the population and genotype levels. However, we don’t (apparently) have quite enough in- formation to estimate the variation in clipping and nutrient effects, or their interaction, at the genotype or population levels. There is a strong overall positive effect of nutrients and a slightly weaker negative effect of clipping. The interaction between clipping and nutrients is only weakly supported (i.e. the p-value is not very small), but it is positive and about the same magnitude as the clipping effect, which is consistent with the statement that “nutrients cancel out the effect of herbivory”.</p>

<div class="rmdcode">
<p><strong>Exercise</strong></p>
<ul>
<li>Re-do the analysis with region as a fixed effect.</li>
<li>Re-do the analysis with a one-way layout as suggested above</li>
</ul>
</div>
</div>
<div id="happy-generalized-mixed-modelling" class="section level3" number="6.2.10">
<h3><span class="header-section-number">6.2.10</span> Happy generalized mixed-modelling</h3>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-93"></span>
<img src="images/Thorn.png" alt="A GLMM character" width="50%" />
<p class="caption">
Figure 6.14: A GLMM character
</p>
</div>

</div>
</div>
<!-- </div> -->
<h3>References</h3>
<div id="refs" class="references hanging-indent">
<div id="ref-banta_comprehensive_2010">
<p>Banta, J. A., M. H. H. Stevens, and M. Pigliucci. 2010. A comprehensive test of the “limiting resources” framework applied to plant tolerance to apical meristem damage. Oikos 119:359–369.</p>
</div>
<div id="ref-bolker_generalized_2009">
<p>Bolker, B. M., M. E. Brooks, C. J. Clark, S. W. Geange, J. R. Poulsen, M. H. H. Stevens, and J.-S. S. White. 2009. Generalized linear mixed models: A practical guide for ecology and evolution. Trends in Ecology and Evolution 24:127–135.</p>
</div>
<div id="ref-elston2001">
<p>Elston, D. A., R. Moss, T. Boulinier, C. Arrowsmith, and X. Lambin. 2001. Analysis of aggregation, a worked example: Numbers of ticks on red grouse chicks. Parasitology 122:563–569.</p>
</div>
<div id="ref-R-DHARMa">
<p>Hartig, F. 2022. DHARMa: Residual diagnostics for hierarchical (multi-level / mixed) regression models.</p>
</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="6.1-lecture-5.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="7-introduction-to-bayesian-inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/BIO8940-uOttawa/class_book/02_03-intro_glmm.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIO8940_book.pdf", "BIO8940_book.epub", "BIO8940_book.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
